### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by jenslind** [oddhill/oddenvironment#13]
Would be nice to keep a changelog of some sort.

**Comment by olofbokedal** [comment]
Agreed. This in combination with releases would be nice.

http://keepachangelog.com/
http://semver.org

The `oddenv` command would need to fetch the latest release instead of commit if we implement this though. Perhaps focus this issue on a change log and create another one for versioning later on? The change log could be grouped by date instead of versions in the meantime.

**Comment by jenslind** [comment]
Fixed :cat2:
